# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 04:59
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='title', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
